### ISSUE TITLE
Unable to get AutoDownloader.js target directory to work on Windows machine.

### ISSUE THREAD

**Issue by llknoksll** [airdcpp-web/airdcpp-apisocket-js#1]
Hey.. I have not been able to get AutoDownloader.js target directory to work on Windows machine. It just downloads results to the default download location.

Using Node v5.10.1. Everything else is working spot on and output from Node terminal is showing the correct location at the POST (SUCCEED). However, the download is added to Download Queue with the location set to default again.

**Comment by maksis** [comment]
Yeah, there was a typo in the example. The download directory should be named as `target_directory` instead of `target`.
