### ISSUE TITLE
Is this the right module for a standalone web app?

### ISSUE THREAD

**Issue by rishighan** [airdcpp-web/airdcpp-apisocket-js#14]
First off, thanks for the excellent documentation, it is a rare and a beautiful thing.
I am building a web app that will integrate with AirDCPP, to initiate searches, surface download statuses etc.

Should I use this module or https://github.com/airdcpp-web/airdcpp-create-extension ?
I intend to customize the UI around it heavily and hence why I thought this library makes more sense.

**Comment by maksis** [comment]
Is your web app going to be just static files that are served to the browser or something else? airdcpp-create-extension will just launch a node process and I guess that you could also use it to launch a web server that will serve your files, but you can also serve the files with a standalone web server. It depends very much on the technologies that you are planning to use. The current Web UI consists of static files and uses this project to connect to the API.

**Comment by rishighan** [comment]
It is a comic book curation app. The stack is React/Redux and Express. So it isn't just static files, the express server is more of a facade that speaks to a couple of microservices.

The idea is that AirDC++ could be running on a NAS or any other platform and my app can simply talk to it through the integration (whatever shape that takes)

Architecture-wise, I wasn't sure what the best route was:
1. The[ remote extension](https://github.com/airdcpp-web/airdcpp-extension-js#remote-extension) way, 
2. The [airdcpp-websocket](https://github.com/airdcpp-web/airdcpp-apisocket-js) way, which seems to make the most sense. However, I couldn't find specific examples, so if you could point me in the right direction, that would be awesome.

**Comment by maksis** [comment]
The obvious example for implementing a standalone UI with this project is the [standard Web UI](https://github.com/airdcpp-web/airdcpp-webui) that is shipped with the application itself. You'll just initialize the socket ([code](https://github.com/airdcpp-web/airdcpp-webui/blob/master/src/services/SocketService.ts)) and then perform authentication ([you can pass username and password to the `connect` method](https://github.com/airdcpp-web/airdcpp-apisocket-js/blob/master/GUIDE.md#connect)). Would that work for you?

**Comment by rishighan** [comment]
Sounds good! Thanks for the pointers.

**Comment by maksis** [comment]
Depending on the scope of your integration, I also wouldn't count out [the REST API](https://github.com/airdcpp-web/airdcpp-apidocs/blob/master/communication-protocols.md#communicating-via-http). Then you don't need to worry about the complexities of websockets (e.g. handling cases when the browser loses connectivity to AirDC++). You would lose event subscriptions though so you need to rely on polling instead.

**Comment by rishighan** [comment]
Thanks, but do you feel that the typical use case in my app:

1. Surfacing search results based on a queried `comic` resource
2. Subsequent download triggered upon user action
3. Status of the said download

would benefit more from a `WebSockets` approach or a `REST` one?

I use `sockets.io` elsewhere in my app to communicate with one of the microservices and there is the benefit of lower latency, which makes for a better UX. Do you think, in your experience building the webapp UI for AirDC++, that `REST` is more beneficial to my use case?

**Comment by maksis** [comment]
Yeah, the socket approach is better in terms of the UX. If the AirDC++ integration is an important part of your project, go with it (especially if you may extend the scope at some point).
