### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by rishighan** [airdcpp-web/airdcpp-apisocket-js#17]
Is there any prerequisite to making `Websocket` work in the browser with `airdcpp-socket`?
Specifically, I am looking at https://github.com/airdcpp-web/airdcpp-webui/blob/master/src/services/SocketService.ts#L28

To begin with, I have the exact same implementation, but I keep getting `Webpack` errors: `Uncaught ReferenceError: process is not defined` I understand that this is a `node` related error, but what gives?

**Comment by rishighan** [comment]
That was it! Damn you are fast! I imagine removing references to `process` should be okay for now.

**Comment by maksis** [comment]
I'd say that this is something that needs fixing....

**Comment by rishighan** [comment]
I'm puzzled as to why you need to check for `process` vars in the browser, given that the web-ui would always run in the browser, right? 

That said, what do you suggest I do? Fork and remove the check?

**Comment by maksis** [comment]
> That said, what do you suggest I do? Fork and remove the check?

Use any workaround that works until a fixed version is available

**Comment by maksis** [comment]
This should be fixed in version 2.4.2
