### ISSUE TITLE
Documentation on event listeners

### ISSUE THREAD

**Issue by rishighan** [airdcpp-web/airdcpp-apisocket-js#20]
Hi, I was wondering where I could find the documentation for event listeners for `socket`-based approaches.
Specifically one such example is:

```typescript
SocketService.addListener(
    `search/${instance.id}`,
    "search_hub_searches_sent",
    async (searchInfo) => {
      // Collect the results for 5 seconds before fetching them
      dispatch({
        type: AIRDCPP_HUB_SEARCHES_SENT,
      });
    },
  );

```

Is there an event listener for when a search instance is created? Or for when a user is successfully authenticated?

**Comment by maksis** [comment]
https://airdcpp.docs.apiary.io/#reference/searching/event-listeners/search-instance-created
https://airdcpp.docs.apiary.io/#reference/sessions/event-listeners/session-created

Do those help?

**Comment by maksis** [comment]
And generic usage information for event listeners: https://github.com/airdcpp-web/airdcpp-apisocket-js/blob/master/GUIDE.md#event-listeners

**Comment by rishighan** [comment]
> https://airdcpp.docs.apiary.io/#reference/searching/event-listeners/search-instance-created
> https://airdcpp.docs.apiary.io/#reference/sessions/event-listeners/session-created
> 
> Do those help?

Thanks!

For this piece of code:

```typescript
SocketService.addListener("sessions", "session_created", (data) => {
      dispatch({
          type: AIRDCPP_SESSION_CREATED,
      });
  });
```

I see the console message `"POST" – "sessions/listeners/session_created" – "(no data)"` indicating that the listener was added, however the redux action is never dispatched. I don't think that the code is ever executed, is it because the event never fired?

**Comment by maksis** [comment]
`"POST" – "sessions/listeners/session_created" – "(no data)" ` only means that the listener was added

> I don't think that the code is ever executed, is it because the event never fired?

Most likely yes. Did you try to log in after adding the listener?

**Comment by rishighan** [comment]
So, this is the complete code:

```typescript
export const search = (data: SearchData) => async (dispatch) => {
  await SocketService.connect("admin", "password", true);
  const instance: SearchInstance = await SocketService.post("search");

  SocketService.addListener("sessions", "session_created", (data) => {
    console.log(data);
    dispatch({
      type: AIRDCPP_SESSION_CREATED,
    });
  });
  SocketService.addListener(
    `search/${instance.id}`,
    "search_hub_searches_sent",
    async (searchInfo) => {
      // Collect the results for 5 seconds before fetching them
      dispatch({
        type: AIRDCPP_HUB_SEARCHES_SENT,
      });
    },
  );

  await SocketService.post<SearchResponse>(
    `search/${instance.id}/hub_search`,
    data,
  );

  await sleep(10000);
  const results = await SocketService.get(`search/${instance.id}/results/0/25`);
  dispatch({
    type: AIRDCPP_SEARCH_RESULTS_RECEIVED,
    results,
  });
  SocketService.disconnect();
  return results;
};
```

Only the `search_hub_searches_sent` is ever fired. When in fact, I see that 

```console
[Log] 1 – "POST" – "sessions/authorize" – {username: "admin", password: "(hidden)", grant_type: "password"} (main.bundle.js, line 9817)
[Log] 1 – "SUCCEEDED" – {auth_token: "335855c4-eb4c-43a1-b2b5-44035c2b9a7b", refresh_token: "cfa1145a-3b61-45d8-bf8c-811022b08fb3", session_id: 4178791853, …} (main.bundle.js, line 9817)
{auth_token: "335855c4-eb4c-43a1-b2b5-44035c2b9a7b", refresh_token: "cfa1145a-3b61-45d8-bf8c-811022b08fb3", session_id: 4178791853, system_info: Object, token_type: "Bearer", …}Object
[Info] Login succeed (main.bundle.js, line 9817)
[Log] 2 – "POST" – "search" – "(no data)" (main.bundle.js, line 9817)
```

`authorization` and `search` are both getting _fired_ ?

What I want to do is just surface those statuses in the UI while I am waiting on the results to be collected and shown.
