### ISSUE TITLE
AutoDownloader.js - Multiple Queries

### ISSUE THREAD

**Issue by vestingz** [airdcpp-web/airdcpp-apisocket-js#3]
AutoDownloader.js does not recurse through multiple queries specified:

const searchItems = [

```
    {
            query: {
                    pattern: 'query01',
                    file_type: 'directory'
            },
            downloadData: {
                    target_directory: '/home/user/Downloads',
            }
    }, {
            query: {
                    pattern: 'query02',
                    file_type: 'directory'
            },
            downloadData: {
                    target_directory: '/home/user/Downloads',
            }
    }, {
            query: {
                    pattern: 'query03',
                    file_type: 'directory'
            },
            downloadData: {
                    target_directory: '/home/user/Downloads',
            }
    }, {
            query: {
                    pattern: 'query04',
                    file_type: 'directory'
            },
            downloadData: {
                    target_directory: '/home/user/Downloads',
    }
```

];

Currently, the script seems to execute only the last query (pattern: 'query04'). Log output does not even mention the first three items.

**Comment by maksis** [comment]
It will choose a random item to search for: https://github.com/airdcpp-web/airdcpp-apisocket-js/blob/master/examples/AutoDownloader.js#L80-L81

Note that it's only an example script for demonstrating API capabilities.

**Comment by llknoksll** [comment]
Just create a list of items then get script to perform individual searches replacing search pattern and location each time :)

**Comment by vestingz** [comment]
Yes, i was figuring the same but have to introduce myself to Javascript first ;)
Another idea i had was to write a little Bash script which injects the search pattern from a list in the .js-file and then runs it.

**Comment by maksis** [comment]
Here's a really simple API connector that uses plain HTTP calls: https://gist.github.com/maksis/f498208401d5bd933dc4eaf41a9685cd

The connector functionality is somewhat compatible with the socket version, it's just more limited (you can't add listeners and so on). It's still sufficient for simple use cases, such as refreshing share, posting chat message, performing searches and so on.

It should be easy to write something similar in other languages as well. Just authenticate, send `Authentication` header field with every request and remember to keep the session alive (note that calls to `session/v0/activity` will return an error in pre-1.3.0 versions but it will still keep the session alive).

**Comment by maksis** [comment]
API documentation is now available at http://docs.airdcpp.apiary.io
